const actions = {
    // Spinner
    SPINNER_ACTIVE: "SPINNER_ACTIVE",
    SPINNER_DISABLED: "SPINNER_DISABLED",

    // LOGOUT
    USER_LOGIN: "USER_LOGIN",
    USER_LOGOUT: "USER_LOGOUT",
    OPEN_MODAL: "OPEN_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL",

    // RECIPE
    FETCHED_RECIPES: "FETCHED_RECIPES",

};

export default actions;
