const actions = {
  // Spinner
  SPINNER_ACTIVE: "SPINNER_ACTIVE",
  SPINNER_DISABLED: "SPINNER_DISABLED",

  //   REGISTER_SUCCESS: "REGISTER_SUCCESS",
  //   REGISTER_FAIL: "REGISTER_FAIL",
  //   LOGIN_SUCCESS: "LOGIN_SUCCESS",
  //   LOGIN_FAIL: "LOGIN_FAIL",
  //   LOGOUT_SUCCESS: "LOGOUT_SUCCESS",

  // RECIPE
  FETCHED_RECIPES: "FETCHED_RECIPES",
  USER_RECIPES: "USER_RECIPES",

  //INGREDIENTS
  FETCHED_INGREDIENTS: "FETCHED_INGREDIENTS",
  FETCHED_CATEGORIES: "FETCHED_CATEGORIES",

  // FILTER
  SORT_VALUE: "SORT_VALUE",
  SEARCH_RECIPE: "SEARCH_RECIPE",
  INGREDIENT_VALUE: "INGREDIENT_VALUE",
  CATEGORY_VALUE: "CATEGORY_VALUE",

  // BAD_INPUT
  SEARCH_RECIPE_BAD_INPUT: "SEARCH_RECIPE_BAD_INPUT",
  BAD_INPUT: "BAD_INPUT",

  RECIPE_LOADING: "RECIPE_LOADING",
  GET_RECIPES: "GET_RECIPES",
  GET_DETAIL_RECIPE: "GET_DETAIL_RECIPE",
  CLEAR_RECIPE: "CLEAR_RECIPE",
  CREATE_RECIPE: "CREATE_RECIPE",
  EDIT_RECIPE: "EDIT_RECIPE",
  DELETE_RECIPE: "DELETE_RECIPE",
  LIKE_RECIPE: "LIKE_RECIPE",
  SAVE_RECIPE: "SAVE_RECIPE",

  ADD_INGREDIENTS: "ADD_INGREDIENTS",
  ADD_MEASUREMENT: "ADD_MEASUREMENT",
  ADD_QUANTITY: "ADD_QUANTITY",
  ADD_INSTRUCTIONS: "ADD_INSTRUCTIONS",
  ADD_COOK_TIME: "ADD_COOK_TIME",
  ADD_CATEGORY: "ADD_CATEGORY",
  GET_CATEGORIES: "GET_CATEGORIES",
  ADD_PICTURE: "ADD_PICTURE",

  USER_LOADING: "USER_LOADING",
  USER_LOADED: "USER_LOADED",
  EDIT_USER: "EDIT_USER",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  GET_SAVED_RECIPES: "GET_SAVED_RECIPES",
  GET_USER_RECIPES: "GET_USER_RECIPES",
  // LOGOUT
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  // RECIPE
  FETCHED_RECIPES: "FETCHED_RECIPES",

  //LIKE

  ADD_LIKE: "ADD_LIKE",
  REMOVE_LIKE: "REMOVE_LIKE",
};

export default actions;
