const actions = {
  // Spinner
  SPINNER_ACTIVE: "SPINNER_ACTIVE",
  SPINNER_DISABLED: "SPINNER_DISABLED",

  //   REGISTER_SUCCESS: "REGISTER_SUCCESS",
  //   REGISTER_FAIL: "REGISTER_FAIL",
  //   LOGIN_SUCCESS: "LOGIN_SUCCESS",
  //   LOGIN_FAIL: "LOGIN_FAIL",
  //   LOGOUT_SUCCESS: "LOGOUT_SUCCESS",

  //   GET_ERRORS: "GET_ERRORS",
  //   CREATE_MESSAGE: "CREATE_MESSAGE",
  //   CLEAR_MESSAGE: "CLEAR_MESSAGE",

  RECIPE_LOADING: "RECIPE_LOADING",
  GET_RECIPES: "GET_RECIPES",
  GET_DETAIL_RECIPE: "GET_DETAIL_RECIPE",
  CLEAR_RECIPE: "CLEAR_RECIPE",
  CREATE_RECIPE: "CREATE_RECIPE",
  EDIT_RECIPE: "EDIT_RECIPE",
  DELETE_RECIPE: "DELETE_RECIPE",
  LIKE_RECIPE: "LIKE_RECIPE",
  SAVE_RECIPE: "SAVE_RECIPE",

  ADD_INGREDIENT: "ADD_INGREDIENT",
  ADD_MEASUREMENT: "ADD_MEASUREMENT",
  ADD_QUANTITY: "ADD_QUANTITY",
  ADD_INSTRUCTIONS: "ADD_INSTRUCTION",
  ADD_COOKTIME: "ADD_COOKTIME",
  ADD_CATEGORY: "ADD_CATEGORY",
  GET_CATEGORIES: "GET_CATEGORIES",
  ADD_PICTURE: "ADD_PICTURE",

  USER_LOADING: "USER_LOADING",
  USER_LOADED: "USER_LOADED",
  EDIT_USER: "EDIT_USER",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  GET_SAVED_RECIPES: "GET_SAVED_RECIPES",
  GET_USER_RECIPES: "GET_USER_RECIPES",
  // LOGOUT
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  // RECIPE
  FETCHED_RECIPES: "FETCHED_RECIPES",
};

export default actions;
